"""Update IPO schema with new fields

Revision ID: 9c3a60089541
Revises: 24e853d1c591
Create Date: 2024-12-30 15:58:11.514005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3a60089541'
down_revision: Union[str, None] = '24e853d1c591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipo', sa.Column('applicant_name', sa.String(length=100), nullable=True))
    op.add_column('ipo', sa.Column('company_name', sa.String(length=100), nullable=True))
    op.add_column('ipo', sa.Column('shares_allotted', sa.Integer(), nullable=True))
    op.add_column('ipo', sa.Column('adjusted_amount', sa.Float(), nullable=True))
    op.add_column('ipo', sa.Column('refund_amount', sa.Float(), nullable=True))
    op.add_column('ipo', sa.Column('updated_at', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ipo', 'updated_at')
    op.drop_column('ipo', 'refund_amount')
    op.drop_column('ipo', 'adjusted_amount')
    op.drop_column('ipo', 'shares_allotted')
    op.drop_column('ipo', 'company_name')
    op.drop_column('ipo', 'applicant_name')
    # ### end Alembic commands ###
